name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        profile:
          - basic
          - pandas
          - advanced

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            REQUIREMENTS=${{ matrix.profile }}
          tags: |
            eden7tech/python-executor:${{ matrix.profile }}
